<?php /* @var Stuntcoders_Wprest_Block_Category $this */ ?>

<div class="archive">
    <main class="site-main">
        <?php foreach ($this->getPosts() as $post): ?>
            <?php echo $this->getLayout()->createBlock('stuntcoders_wprest/post')->setTemplate('stuntcoders/wprest/category/post.phtml')->setPost($post)->toHtml(); ?>
        <?php endforeach; ?>

        <?php $prev = $this->getPrevPageUrl(); ?>
        <?php $next = $this->getNextPageUrl(); ?>
        <?php if ($prev || $next): ?>
            <nav class="navigation paging-navigation medium-8 columns" role="navigation">
                <div class="nav-links">
                    <?php if ($prev): ?>
                        <div class="nav-previous button">
                            <a href="<?php echo $prev; ?>">
                                <span class="meta-nav">&larr;</span>
                                <?php echo $this->__('Newer posts'); ?>
                            </a>
                        </div>
                    <?php endif; ?>
                    <?php if ($next): ?>
                        <div class="nav-next button">
                            <a href="<?php echo $next; ?>">
                                <?php echo $this->__('Older posts'); ?>
                                <span class="meta-nav">&rarr;</span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </nav>
        <?php endif; ?>
    </main>
</div>
